version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: quiz_app_sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=QuizAppSecretPassword@934u2j932
      - MSSQL_TCP_PORT=1433
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:7.0
    container_name: quiz_app_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--noauth"]

  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz_app_webapi
    ports:
      - "5028:80"
    depends_on:
      - sqlserver
      - mongodb
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__QuizApp=Server=sqlserver;Database=QuizApp;User Id=sa;Password=QuizAppSecretPassword@934u2j932;TrustServerCertificate=True;MultipleActiveResultSets=true
      - MongoDB__ConnectionString=mongodb://mongodb:27017
      - MongoDB__DatabaseName=QuizAppImages

volumes:
  sqlserver_data:
  mongodb_data: